2023-04-12 15:42:10,066 ERROR: Exception on /login [GET] [in /Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/wangsj/J/100_Learning/99_playground/Learning-on-The-Flask-Mega-Tutorial/microblog/app/routes.py", line 56, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/wangsj/J/100_Learning/99_playground/Learning-on-The-Flask-Mega-Tutorial/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/wangsj/J/100_Learning/99_playground/Learning-on-The-Flask-Mega-Tutorial/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/wangsj/J/100_Learning/99_playground/Learning-on-The-Flask-Mega-Tutorial/microblog/app/templates/base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/wangsj/miniconda3/envs/microblog/lib/python3.9/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
